# Site Settings
name: martinmayer.tech
title: Martin Mayer | Thoughts on technical leadership
description: Martin Mayer is a technical leader with experience structuring, growing, and guiding high-performing software engineering teams.
tags:
  - technical leadership
  - interim technical leader
  - fractional technical leader
  - high performing software teams
  - inclusive teams
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Portfolio
    url: /portfolio
  - title: Portfolio2
    url: /portfolio2
  - title: Contact
    url: /contact
#  - title: Feed
#    url: /feed.xml
email: martin@martinmayer.tech
# See: https://disqus.com/
disqus_username: martinmayer.tech
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xbjwevyz


# Social Media Settings
# Remove the item if you don't need it
#github_username: martinjmayer
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
linkedin_username: martin-mayer-manchester-uk
#medium_username: medium_username


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: false
  initiatives:
    sort_by: sorting
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Frontend matter defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "initiatives"
    values:
      layout: "initiative"

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
    - initiatives
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version:
#version: v3.1.1
